---
sudo: required

language: python

services:
  - docker

matrix:
  include:
    - name: "Python 2.7 with Ansible<2.0.0"
      env:
        - PY_VER: "2.7"
        - PIP_BIN: pip2
    - name: "Python 3.5"
      env:
        - PY_VER: "3.5"
        - PIP_BIN: pip3
    - name: "Python 3.6"
      env:
        - PY_VER: "3.6"
        - PIP_BIN: pip3
    - name: "Python 3.7"
      env:
        - PY_VER: "3.7"
        - PIP_BIN: pip3

before_install:
  - docker pull "python:${PY_VER}-stretch"

script:
  - >-
    docker run
    -v $PWD:/root/src
    --rm
    "python:${PY_VER}-stretch"
    /bin/sh -c
    "cd /root/src;
    $PIP_BIN install -U setuptools pip;
    $PIP_BIN install -U pytest;
    if [ "$PY_VER" = "2.7" ] ; then $PIP_BIN install -U 'ansible<2.0.0' ; fi;
    $PIP_BIN install -e .[test];
    pytest"
...
# vim:st=2 sts=2 sw=2:
