name: 'Lint it!'
description: 'Lint this repo.'

runs:
  using: "composite"
  steps:
    - name: Create venv.
      run: |
        pushd $HOME
          python3 -m venv --clear .venv-linter
        popd
      shell: bash
    - name: Install dependencies
      run: |
        "$HOME/.venv-linter/bin/python" -m pip install -U setuptools pip
        "$HOME/.venv-linter/bin/python" -m pip install -e .[dev]
      shell: bash
    - name: Test with pytest
      run: |
        "$HOME/.venv-linter/bin/python" -m py.test -m "linter" --lint-code
      shell: bash

