---
name: 'Test it!'
description: 'Test this repo.'

inputs:
  python-version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup test env.
      run: |-
        my_venv_bin="$HOME/.venv${{inputs.python-version}}/bin/python"

        sudo apt-get update -y
        sudo apt-get install -y python3-pip-whl python3-venv
        pushd $HOME
          python${{inputs.python-version}} -m venv --clear .venv${{inputs.python-version}}
        popd

        "$my_venv_bin" -m pip install -U setuptools pip
        "$my_venv_bin" -m pip install -e .[dev]
      shell: bash

    - name: Test with pytest
      run: |-
        "$HOME/.venv${{inputs.python-version}}/bin/python" -m pytest -m "not linter" \
            --cov=./ \
            --cov-report="xml:_reports/coverage-${{inputs.python_version}}.xml"
      shell: bash

    - name: Output req.txt for cache
      run: |-
        "$HOME/.venv${{inputs.python-version}}/bin/python" -m pip freeze > requirements.txt
      shell: bash
...
