name: super-linter

permissions:
  contents: read      # To clone the repository
  packages: read      # To download Docker images from GHCR
  statuses: write     # To report commit statuses
  pull-requests: read # Required for pull_request metadata

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  super-lint:
    name: Super Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Fetch entire history to ensure linters have full context
          fetch-depth: 0
      - name: Run Super-Linter
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: "master"
          GITHUB_TOKEN: ${{ github.token }}
          LINTER_RULES_PATH: .
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_PYLINT: false
