---
name: test

on:
  push:
    branches: [ "*" ]
  pull_request_target:
    branches: [ "master" ]
  schedule:
    - cron: '30 6 * * *'

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ansible-vault-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ansible-vault-${{ runner.os }}-
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: ./.github/actions/test-it
        with:
          python-version: ${{ matrix.python-version }}

      - uses: ./.github/actions/lint-it
        if: ${{ matrix.python-version == '3.9' }}
...
